name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Environment Variables
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: echo "HF_TOKEN is set."

      - name: Format and Lint Code
        run: |
          black . --check
          flake8 . --ignore=E501,F401

      - name: Run Tests
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install pytest
          pytest
